version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
      time: '08:00'
    open-pull-requests-limit: 500
  - package-ecosystem: docker
    directory: '/'
    schedule:
      interval: weekly
      time: '08:00'
    open-pull-requests-limit: 500
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
      time: '08:00'
