apiVersion: argoproj.io/v1aplha1
kind: Application
metadata:
  name: bot-wpp-argo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/GabSnow24/bot-wpp
    targetRevision: HEAD
    path: master
  destination:
    server: https://kubernetes.default.svc
    destination: bot-wpp
  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
