version: '3'

services:
  db:
    container_name: postgres-db-test
    image: postgres
    environment:
      POSTGRES_PASSWORD: "12345"
    ports:
      - "5433:5432"
    volumes:
      - /Users/flamengo
