on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - '**/*.md'
  workflow_dispatch:

name: Standard

jobs:
  deploy:
    name: Deploy to K8S
    if: ${{ success() && github.event_name != 'pull_request_target' && github.event_name != 'push'}}
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub Event Name
        id: github_event_name
        run: echo '${{ github.event_name }}'
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create branch
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "Deploy Action"
          git checkout -b ci_changes
      - name: Kustomize
        uses: imranismail/setup-kustomize@v1
        with:
          kustomize_version: v3.6.1
      - name: Update K8S
        run: |
          cd kube
          cd dev
          kustomize edit set image bot-wpp=qzzdocker24/bot-wpp:${{github.sha}}
      - name: Commit tag
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "Deploy Action"
          git commit -am "chore: change image tag"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: origin HEAD:master --force
          force_with_lease: true
